name: NGINX Webpage CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Build the Docker image for NGINX
    - name: Build Docker image
      run: |
        docker build -t my-nginx-app ./nginx

    # Step 3: Run NGINX container to serve the webpage
    - name: Run NGINX container
      run: |
        docker run -d -p 8080:80 my-nginx-app

    # Step 4: Curl the page to confirm it's running
    - name: Test NGINX container
      run: |
        sleep 5  # Wait for the container to start
        curl http://localhost:8080
